### ISSUE TITLE
Question about expectAttributeAbsent

### ISSUE THREAD

**Issue by kindles** [Medium/dynamite#109]
Hi !

I try to use Dynamite but i'm lost.

How I can check that a username is not taken by another user? I tried with expectAttributeAbsent but it does not work. An idea ?

Thank you :)

```
`app.post('/signup', function (req, res) {
  var user = req.body.user;

  user.userId = uuidV4();
  user.provider = 'local';

  var conditions = client.newConditionBuilder()
    .expectAttributeAbsent('username',user.username) // if the username doesn't exist in the database

  client.putItem('user-table', user)
    .withCondition(conditions)
    .execute()
    .then(function(data){
      console.log(data)
      res.json('work')
    })
    .fail(function(e) {
      console.log(e);
      res.status(500).json({ error: e });
    })
})`
```

cc @nicks

**Comment by nicks** [comment]
expectAttributeAbsent just sets a condition on the row that you're writing on. It doesn't check the whole table.

Please read the DynamoDB Docs, which talk about this in more detail. You'd usually set up a GSI on the username key, and check that.

http://docs.aws.amazon.com/amazondynamodb/latest/gettingstartedguide/Welcome.html
