### ISSUE TITLE
Query by global secondary index?

### ISSUE THREAD

**Issue by Mooser** [Medium/dynamite#64]
Can dynamite query by global secondary indexes?

**Comment by nicks** [comment]
yes, AFAIR you do this by setting the index name to the name of the GSI?
https://github.com/Medium/dynamite/blob/master/lib/QueryBuilder.js#L142

**Comment by Mooser** [comment]
Thanks.  I guess I can trial and error this, but after I set the index name, how do I specify the "equals value" to actually perform the lookup on the index.  Index name is great, but now not sure how to specify what it should equal to using dynamite.

Thanks.

**Comment by xiao** [comment]
You would use it in the same way as you query normal tables (with range key and/or local secondary index). `setIndexName` is the only extra step.

A quick example:
```javascript
var builder = this.newQueryBuilder('table name')
    .setIndexName('GSI index name')
    .setHashKey('GSI hash key name', 'hash key value')
    .indexLessThan('GSI range key name', value) // optional. Checkout `QueryBuilder.js` for all supported comp operators.
```
