### ISSUE TITLE
Support Map data type

### ISSUE THREAD

**Issue by martinraag** [Medium/dynamite#69]
Any specific reason why the Map data type is not supported by this library?

I have just started using the library and would love support for this feature. Maybe someone could explain the complexity involved in adding support.

**Comment by martinraag** [comment]
I started working on support for the Map data type. Lots to do still, but any helpful hints would be welcome. 

https://github.com/Testlio/dynamite/commit/4afc7c309f7cf26ce06b7f546ff7be24ef3f4b3c

**Comment by frostney** [comment]
I would love to see support for Maps. How is it progressing? @martinraag

**Comment by mojo5000** [comment]
Was this ever resolved?

**Comment by adrianlee44** [comment]
This is now resolved with #89
